[package]
name = "risc-v"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
elf = "0.7.4"
fnv = "1.0.7"

[dev-dependencies]
crossbeam = "0.8.2"
