name: Rust

env:
  CARGO_TERM_COLOR: always

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Rust Cache
      uses: Swatinem/rust-cache@v2.7.0
    - name: Build Rust
      run: cargo build --verbose
    - name: Cache Docker images.
      uses: ScribeMD/docker-cache@0.3.6
      with:
        key: docker-${{ runner.os }}-${{ hashFiles('**/Dockerfile') }}
    - name: Build Docker
      working-directory: ./crates/risc-v/resources
      run: docker build -t risc-v-sbi-linux .
    - name: Run Docker
      working-directory: ./crates/risc-v/resources
      run: docker run --rm --privileged -v "$(pwd):/artifacts" risc-v-sbi-linux:latest
    - name: Run Rust tests
      run: cargo test --verbose
